# Generated by Django 2.1.1 on 2018-10-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_descriptive_name', models.CharField(max_length=200, null=True)),
                ('campaign_id', models.IntegerField(null=True)),
                ('campaign_name', models.CharField(max_length=200, null=True)),
                ('campaign_status', models.CharField(max_length=200, null=True)),
                ('city_criteria_id', models.CharField(max_length=200, null=True)),
                ('country_criteria_id', models.IntegerField(null=True)),
                ('customer_descriptive_name', models.CharField(max_length=200, null=True)),
                ('external_customer_id', models.BigIntegerField(null=True)),
                ('is_targeting_location', models.BooleanField(default=True)),
                ('metro_criteria_id', models.CharField(max_length=200, null=True)),
                ('most_specific_criteria_id', models.IntegerField(null=True)),
                ('region_criteria_id', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=200, null=True)),
                ('device', models.CharField(max_length=200, null=True)),
                ('location_type', models.CharField(max_length=200, null=True)),
                ('average_position', models.CharField(max_length=200, null=True)),
                ('clicks', models.IntegerField(null=True)),
                ('conversions', models.CharField(max_length=200, null=True)),
                ('conversion_value', models.FloatField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('impressions', models.IntegerField(null=True)),
                ('interactions', models.IntegerField(null=True)),
                ('interaction_types', models.CharField(max_length=200, null=True)),
                ('video_views', models.IntegerField(null=True)),
            ],
        ),
    ]
