# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountDescriptiveName', models.CharField(max_length=200)),
                ('CampaignId', models.IntegerField()),
                ('CampaignName', models.CharField(max_length=200)),
                ('CampaignStatus', models.CharField(max_length=200)),
                ('CityCriteriaId', models.IntegerField()),
                ('CountryCriteriaId', models.IntegerField()),
                ('CustomerDescriptiveName', models.CharField(max_length=200)),
                ('ExternalCustomerId', models.IntegerField()),
                ('IsTargetingLocation', models.BooleanField(default=True)),
                ('MetroCriteriaId', models.CharField(max_length=200)),
                ('MostSpecificCriteriaId', models.IntegerField()),
                ('RegionCriteriaId', models.IntegerField()),
                ('Date', models.DateField()),
                ('Device', models.CharField(max_length=200)),
                ('LocationType', models.CharField(max_length=200)),
                ('Clicks', models.IntegerField()),
                ('Conversions', models.FloatField()),
                ('ConversionValue', models.FloatField()),
                ('Cost', models.IntegerField()),
                ('Impressions', models.IntegerField()),
                ('Interactions', models.IntegerField()),
                ('InteractionTypes', models.CharField(max_length=200)),
                ('VideoViews', models.IntegerField()),
            ],
        ),
    ]
