# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-09 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='AccountDescriptiveName',
            new_name='account_descriptive_name',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='CampaignId',
            new_name='campaign_id',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='CampaignName',
            new_name='campaign_name',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='CampaignStatus',
            new_name='campaign_status',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='CityCriteriaId',
            new_name='city_criteria_id',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='Clicks',
            new_name='clicks',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='ConversionValue',
            new_name='conversion_value',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='Conversions',
            new_name='conversions',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='Cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='CountryCriteriaId',
            new_name='country_criteria_id',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='CustomerDescriptiveName',
            new_name='customer_descriptive_name',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='Device',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='ExternalCustomerId',
            new_name='external_customer_id',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='Impressions',
            new_name='impressions',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='InteractionTypes',
            new_name='interaction_types',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='Interactions',
            new_name='interactions',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='IsTargetingLocation',
            new_name='is_targeting_location',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='LocationType',
            new_name='location_type',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='MetroCriteriaId',
            new_name='metro_criteria_id',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='MostSpecificCriteriaId',
            new_name='most_specific_criteria_id',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='RegionCriteriaId',
            new_name='region_criteria_id',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='VideoViews',
            new_name='video_views',
        ),
    ]
