# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-17 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20180909_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='average_position',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
