# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20180917_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='account_descriptive_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='average_position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='campaign_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='campaign_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='campaign_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='city_criteria_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='clicks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='conversion_value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='conversions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='cost',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='country_criteria_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='customer_descriptive_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='device',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='external_customer_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='impressions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='interaction_types',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='interactions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='location_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='metro_criteria_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='most_specific_criteria_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='region_criteria_id',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='video_views',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
