# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20180917_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='campaign_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='clicks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='country_criteria_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='external_customer_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='impressions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='interactions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='most_specific_criteria_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='region_criteria_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='video_views',
            field=models.IntegerField(null=True),
        ),
    ]
