# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20180917_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
