# Generated by Django 2.1.1 on 2018-09-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20180925_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
