# Generated by Django 2.1.1 on 2018-10-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20180927_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='conversion_value',
            field=models.FloatField(null=True),
        ),
    ]
