# Generated by Django 2.1.1 on 2018-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='account_descriptive_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='average_position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='campaign_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='campaign_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='campaign_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='city_criteria_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='clicks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='conversion_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='conversions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='country_criteria_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='customer_descriptive_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='device',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='external_customer_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='impressions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='interaction_types',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='interactions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='is_targeting_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='location_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='metro_criteria_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='most_specific_criteria_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='region_criteria_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='video_views',
            field=models.IntegerField(null=True),
        ),
    ]
