from django.db import models

# Create your models here.
class Clients(models.Model):
	account_descriptive_name = models.CharField(max_length=200, null=True)
	campaign_id = models.CharField(max_length=200, null=True)
	campaign_name = models.CharField(max_length=200, null=True)
	campaign_status = models.CharField(max_length=200, null=True)
	city_criteria_id = models.CharField(max_length=200, null=True)
	country_criteria_id = models.CharField(max_length=200, null=True)
	customer_descriptive_name = models.CharField(max_length=200, null=True)
	external_customer_id = models.CharField(max_length=200, null=True)
	is_targeting_location = models.BooleanField(default=True)
	metro_criteria_id = models.CharField(max_length=200, null=True)
	most_specific_criteria_id = models.CharField(max_length=200, null=True)
	region_criteria_id = models.CharField(max_length=200, null=True)
	date = models.CharField(max_length=200, null=True)
	device = models.CharField(max_length=200, null=True)
	location_type = models.CharField(max_length=200, null=True)
	average_position = models.CharField(max_length=200, null=True)
	clicks = models.CharField(max_length=200, null=True)
	conversions = models.CharField(max_length=200, null=True)
	conversion_value = models.CharField(max_length=200, null=True)
	cost = models.CharField(max_length=200, null=True)
	impressions = models.CharField(max_length=200, null=True)
	interactions = models.CharField(max_length=200, null=True)
	interaction_types = models.CharField(max_length=200, null=True)
	video_views = models.CharField(max_length=200, null=True)